### ISSUE TITLE
Last Online Time

### ISSUE THREAD

**Issue by Berisko** [Taronyuu/MinecraftStatistics#1]
Hello, this isn't a issue but request. Sorry... I didn't find a way to create "Pull Requests". I'm not a Java or C+ developer but I'm trying to learn PHP.

**Request:**
Could you add a string or a table who refers to - check player last join time and how long ago it was.

Thank you, Ričards.

**Comment by Taronyuu** [comment]
If I understand you correctly, you want the plugin to store the most recent timestamp of a joined player?

**Comment by Berisko** [comment]
@Taronyuu Yes.

**Comment by Taronyuu** [comment]
Here you go: https://www.spigotmc.org/resources/minecraft-statistics-mysql.25609/update?update=145108

If you like the plugin please submit a review, it shows you appreciation. 😄
