### ISSUE TITLE
Row per every server?

### ISSUE THREAD

**Issue by davutkmbr** [Taronyuu/MinecraftStatistics#2]
First of all thank you for this plugin.

I am using this plugin for BungeeCord. Would not it be more accurate to filter out the list of servers that the player plays instead of 1 row per player?

So each player and one row for each server.

At least I need this, I'm very happy if you can help.
Thank you.

**Comment by Taronyuu** [comment]
The most recent update should add this feature. However, at the moment it is not 100% tested. So use it with caution. (Make a backup of your database)

https://github.com/Taronyuu/MinecraftStatistics/raw/v1.96/out/artifacts/MinecraftStatistics_jar/MinecraftStatistics.jar
